name: issue-greeter
on:
  issues:
    types: [opened]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        env:
          REPO: ${{ github.event.repository.name }}
          OWNER: ${{ github.event.repository.owner.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/hardy4787/LDST/issues/18/comments \
            -d '{"body":"Hello ${{ github.event.issue.user.login }}, thanks for your issue!"}'