name: Reusable .NET Build/Test Workflow
on:
  workflow_call:
    inputs:
      source:
        required: true
        description: "Path to the MS directory"
        type: string
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
