name: Call a reusable workflow

on: push

jobs:

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: hardy4787/LDST/.github/workflows/04-reusable-dotnet-service-build-test.yaml@master
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}