name: Reusable workflow example

on: push

jobs:
  dot_net_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: .

      - name: List of files
        run: |
          ls ${{ github.workspace }}/

      - name: create string
        run: |
          MY_STRING=$(cat << EOF
          |
          6.0.x
          3.1.x
          EOF
          )
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo "::set-output name=content::$MY_STRING"
        id: my_string
      - name: display string
        run: |
          echo "The string is: ${{ steps.my_string.outputs.content }}"

      - name: Read Configuration
        id: configuration
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: ${{ github.workspace }}/sln.build.config.yml
          dotnet-version: '"dotnet-version"'
      - run: |
          echo "DOTNET_VERSIONS=$(echo ["6.0.x","3.1.x"] | egrep "[0-9]" | tr -d "[]" | tr ',' ' ')" >> $GITHUB_ENV

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            3.1.x
