name: Reusable workflow example

on: push

jobs:
  dot_net_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: .

      - name: List of files
        run: |
          ls ${{ github.workspace }}/

      - name: Read Configuration
        id: configuration
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: ${{ github.workspace }}/sln.build.config.yml
          dotnet-services: '"dotnet-services"[]'

      - name: Publish Services
        run: |
          SERVICES='${{ steps.configuration.outputs.dotnet-services }}'
          SERVICES_LENGTH=$(echo "$SERVICES" | jq length)
          my_array=()
          for ((i=0; i<$SERVICES_LENGTH; i++)); do
            project_path=$(echo "$SERVICES" | jq -r ".[$i].project")
            project_name=$(echo "$SERVICES" | jq -r ".[$i].name")
            echo "Publishing $project_path"
            my_array+=("release/$project_name")
          done

          for element in "${my_array[@]}"; do
            echo "$element"
          done
