name: Reusable workflow example

on: push

jobs:
  dot_net_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: .

      - name: Read Configuration
        id: configuration
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: ${{ github.workspace }}/sln.build.config.yml
          dotnet-version: '"dotnet-version"'

      - name: Extract Service Name
        run: |
          KEK='src/Services.Document'
          SERVICE_NAME=${KEK##*.}
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV

      - name: Debug
        run: |
          echo "${{ env.SERVICE_NAME }}"