name: Reusable workflow example

on: push

jobs:
  dot_net_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: .

      - name: Read Configuration
        id: configuration
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: ${{ github.workspace }}/sln.build.config.yml
          dotnet-version: '"dotnet-services"[]'
          solution-name: '"solution-name"'

      - name: Debug
        if: steps.configuration.outputs.dotnet-services != 'null'
        run: |
          SERVICES='${{ steps.configuration.outputs.dotnet-services }}'
          SERVICES_LENGTH=$(echo "$SERVICES" | jq length)
          for ((i=0; i<$SERVICES_LENGTH; i++)); do
            DOCKER=$(echo "$SERVICES" | jq -r ".[$i].docker")
            ENTRYPONT_VALUE=$(echo "$DOCKER" | jq -r '.entrypoint')
            echo "entrypoint_value=$ENTRYPONT_VALUE" >> $GITHUB_ENV
          done

      - name: Use entrypoint value
        run: |
          echo "Entrypoint value: ${{ env.entrypoint_value }}"
